platform :ios, '15.0'

install! 'cocoapods', :deterministic_uuids => true

target 'TesNavIOS' do
  pod 'AMapNavi-NO-IDFA'
  pod 'AMapSearch-NO-IDFA'

  target 'TesNavIOSTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
